### ISSUE TITLE
Documentation and examples of the RAML external config file?

### ISSUE THREAD

**Issue by aviflax** [awslabs/aws-apigateway-swagger-importer#107]
I can’t find this anywhere! Am I missing something?

**Comment by spencerfdavis** [comment]
@aviflax Been kind of a guessing game for me as well.  There are a couple examples in test directory that I have used to help.  (https://github.com/awslabs/aws-apigateway-importer/blob/master/tst/resources/raml/apigateway.json)

**Comment by aviflax** [comment]
@spencerfdavis thank you, that’s super-helpful! I think I get it now.

**Comment by rpgreen** [comment]
Also a working example here: https://github.com/awslabs/api-gateway-secure-pet-store/blob/master/src/main/resources/swagger.yaml

**Comment by aviflax** [comment]
@rpgreen that example is for Swagger, not RAML. It doesn’t illustrate how to create a JSON config file for a RAML API definition. I think it’d be great if you’d at least add to the readme a link to the example that @spencerfdavis pointed to.

**Comment by rpgreen** [comment]
Sorry missed that - yeah that's the best example we have for RAML right now

**Comment by blakeembrey** [comment]
@aviflax @spencerfdavis The JSON format should be exactly the same as what you see in Swagger (the extensions part), except it has to be in an external file of `/<path>/<method>/{auth,integration}`. So the examples in Swagger should easily convert, it's just a bit more verbose because RAML 0.8 has no concept of inlined metadata/extensions/etc.

**Comment by aviflax** [comment]
OK, thanks!
