### ISSUE TITLE
Configure Logging?

### ISSUE THREAD

**Issue by aviflax** [awslabs/aws-apigateway-swagger-importer#124]
I’m really digging this tool for creating and configuring APIs. I consider setting up CloudWatch logging in-scope for this automation, but so far I haven’t found any reference to this in the examples or the code… am I missing something? If not, is this maybe on the roadmap? Come to think of it, is there a roadmap anywhere? Thanks!

**Comment by jackrk** [comment]
To answer your specific questions, you aren't missing something. This tool doesn't support the CloudWatch logging setup operations. The CW Logs settings are on the stage settings which are applied outside of the actual API definition deployment, so it's debatable whether that fits in the scope of the tool. The tool does support doing a basic deployment with a stage name, as I'm sure you've noticed, so you could patch that code with additional parameters since the ApiGateway SDK under the hood supports all operations and settings and is easy to use. 

In terms of roadmap, we don't have one publicly. I'll have to get back to you on adding a feature like this to the importer.

**Comment by aviflax** [comment]
Thanks @jackrk for the thorough and thoughtful response!

**Comment by cfair** [comment]
I wrote a PR to provide this functionality. I haven't merged in any recent changes in a while from mainline. We're using my PR in production and have been for a while with no issues. 

It made sense for us to add the code into the swagger-importer because the logic to parse the swagger file was already in place. The PR I had: https://github.com/awslabs/aws-apigateway-importer/pull/31

**Comment by jackrk** [comment]
Thanks @cfair that seems perfect for @aviflax

**Comment by cfair** [comment]
Sure, no problem. The code was out there so I figured I'd point it out.

One note: the PR I have issued against this repo is missing a commit to make caching work. However, it is in my forked repo in the same branch where I issued the PR from. I also have an additional commit there to allow for the standard AWS credential provider chain, so we could use this on Jenkins.

**Comment by aviflax** [comment]
Thanks @cfair that sounds very promising!

@jackrk any chance of some of the changes making their way into master?

**Comment by jackrk** [comment]
Not in the near future. The feature set on master is pretty much locked, so only bug fixes. It's good to have input from customers on stage management as a part of this tool though!
