### ISSUE TITLE
Please provide a Lambda deployment option?

### ISSUE THREAD

**Issue by petemounce** [awslabs/aws-apigateway-swagger-importer#141]
This tool has immediately helped my team get onboard with using API Gateway. Our use of it is in its infancy.

It would be _sublime_ if you could provide this tool as an AWS Lambda that would regenerate etc our API Gateway APIs etc in reaction to S3 event notifications. That would make our deployment much simpler:
- upload new (source controlled) swagger file to S3
- S3 publishes event to Lambda
- Lambda fetches document(s) from S3 and makes API Gateway reflect that

We could enhance that further by a separate Lambda also publishing the swagger onward to a public repository, but stripped of the vendor extensions like Lambda ARNs and IAM Role ARNs, since that stuff shouldn't be made public.

**Comment by rpgreen** [comment]
This is a great idea but not likely something that API Gateway would own.

Several of our users are currently using a workflow similar to this. It should be fairly trivial to wire up an S3 event/lambda function as you mentioned. The lambda function would need to be owned by your account.

The importer code should work out of the box inside a Java lambda function and should automatically pick up credentials from the Lambda execution role. You may need to implement a simple wrapper/handler to call into the importer code (rather than using the shell script).

Once the API is imported, you can use our REST API to export the API as Swagger without the vendor extensions and publish to the public repo.

Closing this issue but let me know if you have any questions.

**Comment by petemounce** [comment]
@rpgreen sure, fairly trivial, but not nothing, and think of the effort worldwide you'd save us all if AWS offered it out of the box, how eminently bloggable that would be and how slick an introduction to your product paired with AWS Lambda it would be? It would certainly have saved me a couple of hours writing gulp tasks to wrap a java command line tool (which to be fair was mostly my own unfamiliarity with a) maven to get a build going, and b) gulp's task  dependency nuances), and yours is the only real reason I've got java on my workstation. You can infer correctly that I'm not really familiar enough to wrap that up and push it to Lambda with low effort :(

**Comment by rpgreen** [comment]
Totally fair. We have some big things coming down the pipe in the next few weeks. Stay tuned :)
