### ISSUE TITLE
Use importer cross account

### ISSUE THREAD

**Issue by Nr18** [awslabs/aws-apigateway-swagger-importer#168]
Is it possible to: 
- Run a EC2 instance as build server in AWS Account A with a Instance Role.
- Deploy a API using a swagger file to AWS Account B from the EC2 instance from AWS Account A?

Currently it's not possible to assume a role see #146 but can it be done with a workaround? 

I tried setting the environment variable by setting the following before executing the importer:

```
$ AWS_SECRET_ACCESS_KEY=****
$ AWS_SESSION_TOKEN=***
$ AWS_ACCESS_KEY_ID=***
$ ./aws-api-import.sh -c swagger.yaml
```

But it took my configured AWS credentials, i could update the ~/.aws/credentials file with a profile and use that (seemed to work) but then i need to update the file each hour (expiration of the session token)

What is the best approach here?

**Comment by rpgreen** [comment]
Definitely possible. The credentials are loaded in this order:
1. Environment Variables - AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY (RECOMMENDED since they are recognized by all the AWS SDKs and CLI except for .NET), or AWS_ACCESS_KEY and AWS_SECRET_KEY (only recognized by Java SDK)
2. Java System Properties - aws.accessKeyId and aws.secretKey
3. Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI.
4. Instance profile credentials delivered through the Amazon EC2 metadata service

As long as you have means to set the credentials in any of 1-3, they will take precedence over the instance profile.

See http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

**Comment by Nr18** [comment]
Thanks, adding them in the script did the trick:

```
export AWS_SECRET_ACCESS_KEY=****
export AWS_SESSION_TOKEN=****
export AWS_ACCESS_KEY_ID=****
```

I added the following to the aws-api-import.sh file, just wanted to share it for other people.

```
#!/bin/bash
root=$(dirname $(perl -MCwd=abs_path -e 'print abs_path(shift)' $0))

read -p "MFA Token: " TOKEN 
JSON=$(aws sts assume-role --role-arn arn:aws:iam::************:role/MyRole --role-session-name temp --serial-number arn:aws:iam::************:mfa/myuser --output json --token-code ${TOKEN})
export AWS_SECRET_ACCESS_KEY=$(echo ${JSON} | jq -r '.Credentials.SecretAccessKey')
export AWS_SESSION_TOKEN=$(echo ${JSON} | jq -r '.Credentials.SessionToken')
export AWS_ACCESS_KEY_ID=$(echo ${JSON} | jq -r '.Credentials.AccessKeyId')

java -jar $root/target/aws-apigateway-importer-1.0.3-SNAPSHOT-jar-with-dependencies.jar "$@"
```
