### ISSUE TITLE
Stage variable

### ISSUE THREAD

**Issue by Nr18** [awslabs/aws-apigateway-swagger-importer#174]
Is there a way to set stage variable during an create or deploy?

**Comment by kahouieong** [comment]
Unfortunately, the API importer doesn't have ability to create/set stage variable.

**Comment by Nr18** [comment]
So the best solution here is to do a create or update without a deploy and creating the stage via the CLI tools?

BTW, would be a nice +1 to include it as a feature

**Comment by kahouieong** [comment]
To clarify create or update the stage variables, it means assigning the values to stage variables. The stage variables placeholder can be set in a part of swagger document. Changing the stage variables placeholder is required an API deployment.

In order to assign the values to stage variables, you have to create a stage or point the deployment to an existing stage.

There are multiple ways you can assign the values to the stage variables.
For the easiest way to assign the values to a stage, you can do it from API Gateway console.

If you want to automate the process, you can use API Gateway SDK to do so.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
